# setup nltk
python -m nltk.downloader averaged_perceptron_tagger

# train bc gpt2med
python scripts/car_dealer/train_bc.py buyer_bc_gpt2med_test1 gpt2-medium --role=BUYER --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --epochs=36 --lr=0.0001 --train-bsize=32 --grad-accum-steps=4 --inference-bsize=32 --num-logs-per-epoch=4 --num-evals-per-epoch=4 --save-best --save-last --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb
python scripts/car_dealer/train_bc.py seller_bc_gpt2med_test1 gpt2-medium --role=SELLER --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --epochs=36 --lr=0.0001 --train-bsize=32 --grad-accum-steps=4 --inference-bsize=32 --num-logs-per-epoch=4 --num-evals-per-epoch=4 --save-best --save-last --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb

# train bc gpt2xl
python scripts/car_dealer/train_bc.py buyer_bc_gpt2xl_test1 gpt2-xl --role=BUYER --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --epochs=36 --lr=0.0001 --train-bsize=16 --grad-accum-steps=8 --inference-bsize=32 --num-logs-per-epoch=4 --num-evals-per-epoch=4 --save-best --save-last --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb
python scripts/car_dealer/train_bc.py seller_bc_gpt2xl_test1 gpt2-xl --role=SELLER --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --epochs=36 --lr=0.0001 --train-bsize=16 --grad-accum-steps=8 --inference-bsize=32 --num-logs-per-epoch=4 --num-evals-per-epoch=4 --save-best --save-last --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb

python scripts/car_dealer/train_bc.py buyer_bc_gpt2xl_test2 gpt2-xl --role=BUYER --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --epochs=18 --lr=0.00005 --train-bsize=16 --grad-accum-steps=8 --inference-bsize=32 --num-logs-per-epoch=4 --num-evals-per-epoch=4 --save-best-also --save-last --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb
python scripts/car_dealer/train_bc.py seller_bc_gpt2xl_test2 gpt2-xl --role=SELLER --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --epochs=18 --lr=0.00005 --train-bsize=16 --grad-accum-steps=8 --inference-bsize=32 --num-logs-per-epoch=4 --num-evals-per-epoch=4 --save-best-also --save-last --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb

python scripts/car_dealer/train_bc.py buyer_bc_gpt2xl_test4 gpt2-xl --role=BUYER --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --epochs=18 --use-lr-schedule --train-bsize=16 --grad-accum-steps=8 --inference-bsize=32 --num-logs-per-epoch=4 --num-evals-per-epoch=4 --save-best --save-last --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb
python scripts/car_dealer/train_bc.py seller_bc_gpt2xl_test4 gpt2-xl --role=SELLER --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --epochs=18 --use-lr-schedule --train-bsize=16 --grad-accum-steps=8 --inference-bsize=32 --num-logs-per-epoch=4 --num-evals-per-epoch=4 --save-best --save-last --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb

python scripts/car_dealer/eval_seller.py eval--seller_bc_gpt2xl_test4         gpt2-xl bc --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --max-sequence-length=1024 --max-new-tokens=128 --num-samples=500 --save-every=100 --model-p-shape=4 --gcloud-project=rail-tpus --verbose
python scripts/car_dealer/eval_seller.py eval--seller_bc_gpt2xl_test4--sample gpt2-xl bc --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --max-sequence-length=1024 --max-new-tokens=128 --num-samples=500 --save-every=100 --do-sample --model-p-shape=4 --gcloud-project=rail-tpus --verbose
python scripts/car_dealer/eval_seller.py eval--seller_bc_gpt2xl_test4--n2000         gpt2-xl bc --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --max-sequence-length=1024 --max-new-tokens=128 --num-samples=2000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --verbose
python scripts/car_dealer/eval_seller.py eval--seller_bc_gpt2xl_test4--sample--n2000 gpt2-xl bc --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --max-sequence-length=1024 --max-new-tokens=128 --num-samples=2000 --save-every=100 --do-sample --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --verbose


python scripts/car_dealer/eval_seller.py eval--seller_revenue_bc_gpt2xl_test4--sample--n4000 gpt2-xl bc --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --max-sequence-length=1024 --max-new-tokens=128 --num-samples=4000 --save-every=100 --do-sample --model-p-shape=1 --seed=2 --gcloud-project=rail-tpus --verbose


# train frozen mc
python scripts/car_dealer/cache_embs.py embs--seller_bc_gpt2xl_test4--model gpt2-xl --output-path=gcs://rail-tpus-charles-3/ILQL5/embs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --bsize=64 --model-p-shape=4 --gcloud-project=rail-tpus
python scripts/car_dealer/train_frozen_mc.py seller_frozen_mc_gpt2xl_test1 gpt2-xl --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/embs/car_dealer/embs--seller_bc_gpt2xl_test4--model --lm-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --epochs=36 --lr=0.0001 --train-bsize=8 --grad-accum-steps=16 --inference-bsize=8 --num-logs-per-epoch=4 --num-evals-per-epoch=4 --num-saves-per-epoch=4 --save-best --save-last --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb

python scripts/car_dealer/eval_seller.py eval--seller_frozen_mc_gpt2xl_test1--beta01--sample--n2000 gpt2-xl frozen_mc --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_frozen_mc_gpt2xl_test1 --max-sequence-length=1024 --max-new-tokens=128 --beta=1.0 --num-samples=2000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_frozen_mc_gpt2xl_test1--beta04--sample--n2000 gpt2-xl frozen_mc --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_frozen_mc_gpt2xl_test1 --max-sequence-length=1024 --max-new-tokens=128 --beta=4.0 --num-samples=2000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_frozen_mc_gpt2xl_test1--beta08--sample--n2000 gpt2-xl frozen_mc --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_frozen_mc_gpt2xl_test1 --max-sequence-length=1024 --max-new-tokens=128 --beta=8.0 --num-samples=2000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_frozen_mc_gpt2xl_test1--beta16--sample--n2000 gpt2-xl frozen_mc --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_frozen_mc_gpt2xl_test1 --max-sequence-length=1024 --max-new-tokens=128 --beta=16.0 --num-samples=2000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose


python scripts/car_dealer/cache_embs.py embs--revenue--seller_bc_gpt2xl_test4--model gpt2-xl --reward-mode=revenue --output-path=gcs://rail-tpus-charles-3/ILQL5/embs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --bsize=64 --model-p-shape=4 --gcloud-project=rail-tpus
python scripts/car_dealer/train_frozen_mc.py seller_revenue_frozen_mc_gpt2xl_test2 gpt2-xl --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/embs/car_dealer/embs--revenue--seller_bc_gpt2xl_test4--model --lm-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --epochs=36 --lr=0.0001 --train-bsize=8 --grad-accum-steps=16 --inference-bsize=8 --num-logs-per-epoch=4 --num-evals-per-epoch=4 --num-saves-per-epoch=4 --save-best --save-last --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb

TPU0 python scripts/car_dealer/eval_seller.py eval--seller_revenue_frozen_mc_gpt2xl_test1--beta01--sample--n4000 gpt2-xl frozen_mc --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_frozen_mc_gpt2xl_test1 --max-sequence-length=1024 --max-new-tokens=128 --beta=1.0 --num-samples=4000 --save-every=100 --model-p-shape=1 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
TPU1 python scripts/car_dealer/eval_seller.py eval--seller_revenue_frozen_mc_gpt2xl_test1--beta04--sample--n4000 gpt2-xl frozen_mc --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_frozen_mc_gpt2xl_test1 --max-sequence-length=1024 --max-new-tokens=128 --beta=4.0 --num-samples=4000 --save-every=100 --model-p-shape=1 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
TPU2 python scripts/car_dealer/eval_seller.py eval--seller_revenue_frozen_mc_gpt2xl_test1--beta08--sample--n4000 gpt2-xl frozen_mc --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_frozen_mc_gpt2xl_test1 --max-sequence-length=1024 --max-new-tokens=128 --beta=8.0 --num-samples=4000 --save-every=100 --model-p-shape=1 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
TPU3 python scripts/car_dealer/eval_seller.py eval--seller_revenue_frozen_mc_gpt2xl_test1--beta16--sample--n4000 gpt2-xl frozen_mc --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_frozen_mc_gpt2xl_test1 --max-sequence-length=1024 --max-new-tokens=128 --beta=16.0 --num-samples=4000 --save-every=100 --model-p-shape=1 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose



# train ilql
# v4-vm-1
python scripts/car_dealer/train_ilql.py seller_ilql_gpt2xl_tau0p7_cql0p001_test1 gpt2-xl --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --lm-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --tau=0.7 --cql-weight=0.001 --epochs=512 --lr=0.0001 --train-bsize=4 --grad-accum-steps=32 --inference-bsize=4 --num-logs-per-epoch=4 --num-evals-per-epoch=1 --num-saves-per-epoch=1 --save-best-also --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb

python scripts/car_dealer/eval_seller.py eval--seller_ilql_gpt2xl_test1--beta16--sample--n4000 gpt2-xl ilql --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=116430 --max-sequence-length=1024 --max-new-tokens=128 --beta=16.0 --num-samples=4000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_ilql_gpt2xl_test1--beta08--sample--n4000 gpt2-xl ilql --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=116430 --max-sequence-length=1024 --max-new-tokens=128 --beta=8.0 --num-samples=4000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_ilql_gpt2xl_test1--beta04--sample--n4000 gpt2-xl ilql --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=116430 --max-sequence-length=1024 --max-new-tokens=128 --beta=4.0 --num-samples=4000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_ilql_gpt2xl_test1--beta01--sample--n4000 gpt2-xl ilql --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=116430 --max-sequence-length=1024 --max-new-tokens=128 --beta=1.0 --num-samples=4000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose

python scripts/car_dealer/eval_seller.py eval--seller_ilql_gpt2xl_test1_174645--beta16--sample--n4000 gpt2-xl ilql --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=174645 --max-sequence-length=1024 --max-new-tokens=128 --beta=16.0 --num-samples=4000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_ilql_gpt2xl_test1_174645--beta08--sample--n4000 gpt2-xl ilql --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=174645 --max-sequence-length=1024 --max-new-tokens=128 --beta=8.0 --num-samples=4000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_ilql_gpt2xl_test1_174645--beta04--sample--n4000 gpt2-xl ilql --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=174645 --max-sequence-length=1024 --max-new-tokens=128 --beta=4.0 --num-samples=4000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_ilql_gpt2xl_test1_174645--beta01--sample--n4000 gpt2-xl ilql --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=174645 --max-sequence-length=1024 --max-new-tokens=128 --beta=1.0 --num-samples=4000 --save-every=100 --model-p-shape=4 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose

python scripts/car_dealer/eval_seller.py eval--seller_ilql_gpt2xl_test1_430791--beta16--sample--n4000 gpt2-xl ilql --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=430791 --max-sequence-length=1024 --max-new-tokens=128 --beta=16.0 --num-samples=4000 --save-every=100 --model-p-shape=2 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_ilql_gpt2xl_test1_430791--beta08--sample--n4000 gpt2-xl ilql --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=430791 --max-sequence-length=1024 --max-new-tokens=128 --beta=8.0 --num-samples=4000 --save-every=100 --model-p-shape=2 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_ilql_gpt2xl_test1_430791--beta04--sample--n4000 gpt2-xl ilql --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=430791 --max-sequence-length=1024 --max-new-tokens=128 --beta=4.0 --num-samples=4000 --save-every=100 --model-p-shape=2 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_ilql_gpt2xl_test1_430791--beta01--sample--n4000 gpt2-xl ilql --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=430791 --max-sequence-length=1024 --max-new-tokens=128 --beta=1.0 --num-samples=4000 --save-every=100 --model-p-shape=2 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose

python scripts/car_dealer/train_ilql.py seller_revenue_ilql_gpt2xl_tau0p7_cql0p001_test1 gpt2-xl --reward-mode=revenue --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --lm-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --init-value-with-lm --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_frozen_mc_gpt2xl_test1 --tau=0.7 --cql-weight=0.001 --epochs=100 --lr=0.0003 --train-bsize=4 --grad-accum-steps=32 --inference-bsize=4 --num-logs-per-epoch=4 --num-evals-per-epoch=1 --num-saves-per-epoch=1 --save-best-also --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb
python scripts/car_dealer/train_ilql.py seller_revenue_ilql_gpt2xl_tau0p7_cql0p001_test1_2 gpt2-xl --reward-mode=revenue --output-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer --data-path=gcs://rail-tpus-charles-3/ILQL5/data/car_dealer --lm-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=170764 --tau=0.7 --cql-weight=0.001 --epochs=100 --lr=0.0003 --train-bsize=4 --grad-accum-steps=32 --inference-bsize=4 --num-logs-per-epoch=4 --num-evals-per-epoch=1 --num-saves-per-epoch=1 --save-best-also --model-p-shape=4 --gcloud-project=rail-tpus --use-wandb


python scripts/car_dealer/eval_seller.py eval--seller_revenue_ilql_gpt2xl_test1_100906--beta01--sample--n4000 gpt2-xl ilql --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=100906 --max-sequence-length=1024 --max-new-tokens=128 --beta=1.0 --num-samples=4000 --save-every=100 --model-p-shape=2 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_revenue_ilql_gpt2xl_test1_100906--beta04--sample--n4000 gpt2-xl ilql --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=100906 --max-sequence-length=1024 --max-new-tokens=128 --beta=4.0 --num-samples=4000 --save-every=100 --model-p-shape=2 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_revenue_ilql_gpt2xl_test1_100906--beta08--sample--n4000 gpt2-xl ilql --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=100906 --max-sequence-length=1024 --max-new-tokens=128 --beta=8.0 --num-samples=4000 --save-every=100 --model-p-shape=2 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_revenue_ilql_gpt2xl_test1_100906--beta16--sample--n4000 gpt2-xl ilql --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=100906 --max-sequence-length=1024 --max-new-tokens=128 --beta=16.0 --num-samples=4000 --save-every=100 --model-p-shape=2 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose

python scripts/car_dealer/eval_seller.py eval--seller_revenue_ilql_gpt2xl_test1_170764--beta01--sample--n4000 gpt2-xl ilql --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=170764 --max-sequence-length=1024 --max-new-tokens=128 --beta=1.0 --num-samples=4000 --save-every=100 --model-p-shape=2 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_revenue_ilql_gpt2xl_test1_170764--beta04--sample--n4000 gpt2-xl ilql --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=170764 --max-sequence-length=1024 --max-new-tokens=128 --beta=4.0 --num-samples=4000 --save-every=100 --model-p-shape=2 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_revenue_ilql_gpt2xl_test1_170764--beta08--sample--n4000 gpt2-xl ilql --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=170764 --max-sequence-length=1024 --max-new-tokens=128 --beta=8.0 --num-samples=4000 --save-every=100 --model-p-shape=2 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
python scripts/car_dealer/eval_seller.py eval--seller_revenue_ilql_gpt2xl_test1_170764--beta16--sample--n4000 gpt2-xl ilql --reward-mode=revenue --checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_bc_gpt2xl_test4/model --value-checkpoint-path=gcs://rail-tpus-charles-3/ILQL5/outputs/car_dealer/seller_revenue_ilql_gpt2xl_tau0p7_cql0p001_test1 --value-checkpoint-idx=170764 --max-sequence-length=1024 --max-new-tokens=128 --beta=16.0 --num-samples=4000 --save-every=100 --model-p-shape=2 --seed=2 --gcloud-project=rail-tpus --do-sample --verbose
